# (PART) Analyses {-}

# Script Files

## Names

File names should be meaningful and end in `.m`. Avoid using special characters 
in file names - stick with numbers, letters, `-`, and `_`.


    # Good
    fit_models.m
    utility_functions.m

    # Bad
    fit models.M
    foo.m
    stuff.m

If files should be run in a particular order, prefix them with numbers. If it 
seems likely you'll have more than 10 files, left pad with zero:

    00_download.m
    01_explore.m
    ...
    09_model.m
    10_visualize.m

If you later realise that you've missed some steps, it's tempting to use `02a`, 
`02b`, etc. However, I think it's generally better to bite the bullet and 
rename all files.

Pay attention to capitalization, since you, or some of your collaborators, 
might be using an operating system with a case-insensitive file system (e.g., 
Microsoft Windows or OS X) which can lead to problems with (case-sensitive) 
revision control systems. Prefer file names that are all lower case, and never 
have names that differ only in their capitalization.

## Structure 

Use commented lines of `-` and `=` to break up your file into easily readable 
chunks.

```{r, eval = FALSE}
% Load data ---------------------------

% Plot data ---------------------------
```

If your script relies on code outside of the current working directory (e.g. CoreLibrary packages), 
modify the path at the beginning of the file. This is more transparent and reproducible than manually
modifying the path in the matlab application. 

# Functions and Classes

## Names

## Structure
